CXX := g++
CXXFLAGS := -std=c++17 -Wall -Wextra -O2 -g
SRCS := \
  emulator_proj/emulator_main.cpp \
  emulator_proj/cpu.cpp \
  emulator_proj/memory.cpp \
  emulator_proj/page.cpp \
  emulator_proj/register_file.cpp \
  emulator_proj/terminal.cpp \
  emulator_proj/timer.cpp

OBJS := $(SRCS:.cpp=.o)
DEPS := $(OBJS:.o=.d)

emulator: $(OBJS)
	$(CXX) $(CXXFLAGS) -o $@ $(OBJS)

%.o: %.cpp
	$(CXX) $(CXXFLAGS) -MMD -MP -c $< -o $@

-include $(DEPS)

clean:
	rm -f $(OBJS) $(DEPS) emulator

.PHONY: emulator clean
